CREATE TABLE Hotels (
                        id int PRIMARY KEY generated by default as identity ,
                        name VARCHAR(255),
                        city VARCHAR(100)
);

CREATE TABLE Rooms (
                       id int PRIMARY KEY generated by default as identity,
                       hotel_id INTEGER REFERENCES Hotels(id),
                       room_number int,
                       price int

);

CREATE TABLE Flights (
                         id int PRIMARY KEY generated by default as identity,
                         flight_number int,
                         departure_city VARCHAR(100),
                         arrival_city VARCHAR(100),
                         departure_time timestamp,
                         arrival_time TIMESTAMP,
                         price int,
                         airline varchar

);

create table Customers(
                       id int PRIMARY KEY generated by default as identity,
                       customer_name VARCHAR(100),
                       customer_surname varchar,
                       customer_otchestvo varchar,
                       passport_data varchar
);

CREATE TABLE Bookings (
                          id int PRIMARY KEY generated by default as identity,
                          room_id INTEGER REFERENCES Rooms(id),
                          flight_id INTEGER REFERENCES Flights(id),
                          customer_id INTEGER references Customers(id),
                          booking_date TIMESTAMP,
                          check_in_time timestamp,
                          check_out_time timestamp

);
