spring:
  application:
    name: trip-resource-server
  cloud:
    openfeign:
      okhttp:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mts_hack_resource
    username: test
    password: test
trip:
  url:
    employee-directory: "http://localhost:6161"
    booking-service: "http://localhost:7171"
server:
  port: 8181